# Generated by Django 2.1.2 on 2018-11-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cleta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='comuna',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.CharField(max_length=100),
        ),
    ]
