# Generated by Django 2.1.2 on 2018-11-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cleta', '0002_auto_20181107_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='rut',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
