# Generated by Django 2.1.2 on 2018-11-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cleta', '0003_auto_20181107_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_pic',
            new_name='foto_perfil',
        ),
    ]
