# Generated by Django 2.1.2 on 2018-11-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cleta', '0005_auto_20181108_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='foto_perfil',
            field=models.ImageField(upload_to='media'),
        ),
    ]
